#!/bin/sh


# IP-address of the server with application
addr='0.0.0.0'

# Port on the application server
port=56780

# Path to the directory with the application
path=.


if [ ! -f ${path}/app/router.php ] || [ ! -f ${path}/app/console ];
then
    echo "Cent run Application" >&2
    exit 1
fi


stop_server() {
    if [ -f ${path}/bin/.spid ]
    then
        kill `cat ${path}/bin/.spid` 2> /dev/null
        rm ${path}/bin/.spid
    fi
}
stop_task_scheduler() {
    if [ -f ${path}/bin/.tspid ]
    then
        kill `cat ${path}/bin/.tspid` 2> /dev/null
        rm ${path}/bin/.tspid
    fi
}


case "$1" in
    stop)
        stop_server
        stop_task_scheduler
        ;;
    start|reload|restart|force-reload)
        stop_server
        stop_task_scheduler

        # run server
        php -S ${addr}:${port} -t ${path}/web ${path}/app/router.php > /dev/null 2> /dev/null &
        echo $! > ${path}/bin/.spid
        # run task scheduler
        ${path}/app/console animedb:task-scheduler > /dev/null 2> /dev/null &
        echo $! > ${path}/bin/.tspid
        ;;
    *)
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0