#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use AnimeDB\Bundle\CatalogBundle\Command\EventListener;
use AnimeDB\Bundle\CatalogBundle\Command\CheckUpdates;
use AnimeDB\Bundle\CatalogBundle\Command\ScanStorages;
use AnimeDB\Bundle\CatalogBundle\Command\CheckItem;
use AnimeDB\Bundle\CatalogBundle\Command\TaskScheduler;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->add(new EventListener());
$application->add(new CheckUpdates());
$application->add(new ScanStorages());
$application->add(new CheckItem());
$application->add(new TaskScheduler());
$application->run($input);
