#!/bin/sh


# IP-address of the server with application
addr='0.0.0.0'

# Port on the application server
port=56780

# Path to the directory with the application
path=.


run_server() {
    if [ ! -f ${path}/app/router.php ]
    then
        echo "Cent run server" >&2
        exit 1 
    fi
#    php -S ${addr}:${port} -t ${path}/web ${path}/app/router.php > /dev/null 2> /dev/null &
    php -S ${addr}:${port} -t ${path}/web ${path}/app/router.php > /dev/null 2> error.log &
    echo $! > .spid
}

run_task_manager() {
    if [ ! -f ${path}/app/task_manager.php ]
    then
        echo "Cent run task manager" >&2
        exit 1 
    fi
    php -f ${path}/app/task_manager.php > /dev/null 2> /dev/null &
    echo $! > .tmpid
}

stop_server() {
    kill `cat .spid` 2> /dev/null
    rm .spid
}

stop_task_manager() {
    kill `cat .tmpid` 2> /dev/null
    rm .tmpid
}


case "$1" in
    start)
        if [ -f .spid ]
        then
            echo "Server is already running" >&2
            exit 1
        fi
        if [ -f .tmpid ]
        then
            echo "Task manager is already running" >&2
            exit 1
        fi
        run_server
        run_task_manager
        ;;
    stop)
        if [ ! -f .spid ]
        then
            echo "Server is not running" >&2
            exit 1
        fi
        if [ ! -f .tmpid ]
        then
            echo "Task manager is not running" >&2
            exit 1
        fi
        stop_server
        stop_task_manager
        ;;
    reload|restart|force-reload)
        if [ -f .spid ]
        then
            stop_server
        fi
        if [ -f .tmpid ]
        then
            stop_task_manager
        fi
        run_server
        run_task_manager
        ;;
    *)
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
